language:
        - python
python:
        - 2.7
        - "pypy"
dist: trusty
sudo: required

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libtool pkg-config build-essential autoconf automake pkg-config python-pip libguestfs-tools libvirt
        - pip install --upgrade pip
        - pip install configobj coverage clustershell msgpack-python signalfd libvirt-python ipaddr lxml
        - ./misc/travis/install-dependencies.sh
install:
        - ./bootstrap.sh

