language:
        - c
python:
        - 2.7
dist: trusty
sudo: required
compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libtool pkg-config build-essential autoconf automake pkg-config python-pip
        - pip install configobj coverage clustershell msgpack-python signalfd libvirt libguestfs-tools ipaddr lxml
        - ./misc/travis/install-dependencies.sh
install:
        - ./bootstrap.sh

